/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as PianoRouteImport } from './routes/piano'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GuitarRouteImport } from './routes/guitar'
import { Route as GoldenBrownRouteImport } from './routes/golden-brown'
import { Route as IndexRouteImport } from './routes/index'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoRoute = PianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GuitarRoute = GuitarRouteImport.update({
  id: '/guitar',
  path: '/guitar',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldenBrownRoute = GoldenBrownRouteImport.update({
  id: '/golden-brown',
  path: '/golden-brown',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/golden-brown': typeof GoldenBrownRoute
  '/guitar': typeof GuitarRoute
  '/import': typeof ImportRoute
  '/instruments': typeof InstrumentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/online': typeof OnlineRoute
  '/piano': typeof PianoRoute
  '/songs': typeof SongsRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/golden-brown': typeof GoldenBrownRoute
  '/guitar': typeof GuitarRoute
  '/import': typeof ImportRoute
  '/instruments': typeof InstrumentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/online': typeof OnlineRoute
  '/piano': typeof PianoRoute
  '/songs': typeof SongsRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/golden-brown': typeof GoldenBrownRoute
  '/guitar': typeof GuitarRoute
  '/import': typeof ImportRoute
  '/instruments': typeof InstrumentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/online': typeof OnlineRoute
  '/piano': typeof PianoRoute
  '/songs': typeof SongsRoute
  '/studio': typeof StudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/golden-brown'
    | '/guitar'
    | '/import'
    | '/instruments'
    | '/library'
    | '/login'
    | '/online'
    | '/piano'
    | '/songs'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/golden-brown'
    | '/guitar'
    | '/import'
    | '/instruments'
    | '/library'
    | '/login'
    | '/online'
    | '/piano'
    | '/songs'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/golden-brown'
    | '/guitar'
    | '/import'
    | '/instruments'
    | '/library'
    | '/login'
    | '/online'
    | '/piano'
    | '/songs'
    | '/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoldenBrownRoute: typeof GoldenBrownRoute
  GuitarRoute: typeof GuitarRoute
  ImportRoute: typeof ImportRoute
  InstrumentsRoute: typeof InstrumentsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OnlineRoute: typeof OnlineRoute
  PianoRoute: typeof PianoRoute
  SongsRoute: typeof SongsRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano': {
      id: '/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof PianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guitar': {
      id: '/guitar'
      path: '/guitar'
      fullPath: '/guitar'
      preLoaderRoute: typeof GuitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golden-brown': {
      id: '/golden-brown'
      path: '/golden-brown'
      fullPath: '/golden-brown'
      preLoaderRoute: typeof GoldenBrownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoldenBrownRoute: GoldenBrownRoute,
  GuitarRoute: GuitarRoute,
  ImportRoute: ImportRoute,
  InstrumentsRoute: InstrumentsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OnlineRoute: OnlineRoute,
  PianoRoute: PianoRoute,
  SongsRoute: SongsRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
